Add all the basic files needs for the project set up
ASU-CodeDevils/scraper.codedevils.org pull request #1
Opened 2024-08-29 20:20 UTC by frankjlin16

This pull request adds the necessary dependencies for Docker Compose, MySQL connector, and Testcontainers. These dependencies are required for running the application in a Docker environment and for testing with Testcontainers.

Also, this pull request includes a license and readme for the projects.

2024-08-30 00:32 UTC, reharri7 commented
Should I try running this?

2024-08-30 00:38 UTC, frankjlin16 commented
> Should I try running this?

If you could @reharri7, I'd really appreciate it.

2024-08-30 00:44 UTC, Remi-Godin requested changes, later dismissed
Add `.env` to `.gitignore`.

2024-08-30 00:44 UTC, Remi-Godin commented on example.compose.yml
Maybe we should have a template `.env` file instead?
i.e.:
```yaml
# docker-compose.yaml
services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - 3306
```

```shell
# template.env
MYSQL_ROOT_PASSWORD="my_root_password"
MYSQL_DATABASE="my_db_name"
MYSQL_USER="username"
MYSQL_PASSWORD="password"
```
Would need to add `.env` to `.gitignore`. Then a user just has to copy the `template.env` file, remove the `template` part, and change the variables.

2024-08-30 00:44 UTC, Remi-Godin commented on src/main/resources/example.application.properties
Can this `.properties` file read from the environment? If so, we could set it up for it along with the docker compose file. It would prevent us from having to change variables in multiple locations.

2024-08-30 00:44 UTC, Remi-Godin commented on README.md
If we do add a `.env` file, then we can remove the steps requiring to create a new docker-compose file since it will be the same for everyone. If it applies for the `.properties` file, then we can remove those steps too. Would make it a lot easier for our users to setup.

2024-08-30 00:53 UTC, reharri7 commented on README.md
> +The Job Scraper Project is designed to create a comprehensive system for scraping job postings from various websites and serving the collected data through an API built with Spring Boot. The project
SpringBoot * I think

2024-08-30 00:53 UTC, reharri7 commented on example.compose.yml
> +services:
New line EOF

2024-08-30 00:54 UTC, reharri7 commented on example.compose.yml
I agree

2024-09-06 01:33 UTC, frankjlin16 commented
The new commits implement the usage of a .env file. README.md has also be updated to reflect this change.
@reharri7 @Remi-Godin

2024-09-06 01:36 UTC, reharri7 approved these changes

2024-09-06 01:40 UTC, merged